version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: java-app-prod-container
    ports:
      - "8080:8080"
    depends_on:
      mariadb-prod:
        condition: service_healthy
    environment:
      - PROFILE=prod
      - DB_URL=${DB_URL:-jdbc:mariadb://mariadb-prod:3306/myapp}
      - DB_USERNAME=${DB_USERNAME:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - JAVA_OPTS=-server -Xms256m -Xmx1024m -XX:+UseG1GC
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  mariadb-prod:
    image: mariadb:10.11
    container_name: mariadb-prod-container
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MARIADB_DATABASE: ${DB_NAME:-myapp}
      MARIADB_USER_FILE: /run/secrets/db_user
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_user
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 --silent"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - mariadb-prod-data:/var/lib/mysql
      - ./db/prod:/docker-entrypoint-initdb.d:ro
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - prod-network

  # Production monitoring (optional)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-prod
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600  # Check every hour
    restart: unless-stopped
    networks:
      - prod-network

volumes:
  mariadb-prod-data:
    driver: local

networks:
  prod-network:
    driver: bridge

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user:
    file: ./secrets/db_user.txt
  db_password:
    file: ./secrets/db_password.txt