version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: java-app-dev-container
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - PROFILE=dev
      - DB_URL=jdbc:mariadb://mariadb:3306/myapp
      - DB_USERNAME=appuser
      - DB_PASSWORD=apppassword
    volumes:
      - ./src:/app/src:ro  # Mount source for hot reload (if supported)
    restart: unless-stopped
    networks:
      - dev-network

  mariadb:
    image: mariadb:10.11
    container_name: mariadb-dev-container
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: myapp
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mariadb-dev-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d:ro  # Dev seed data
    restart: unless-stopped
    networks:
      - dev-network

  # Optional: Database admin tool for development
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-dev-container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dev-network

volumes:
  mariadb-dev-data:

networks:
  dev-network:
    driver: bridge