version: '3.9'

services:
  app:
    build: .
    container_name: java-app-container
    ports:
      - "8082:8080"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: myapp
      DB_USER: appuser
      DB_PASSWORD: apppassword
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: myapp
      MARIADB_USER: appuser
      MARIADB_PASSWORD: apppassword
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 2
    volumes:
      - mariadb-data:/var/lib/mysql

  #redis:
    #image: redis
    #container_name: redis-container
  
volumes:
  mariadb-data:

