apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: java-app
type: Opaque
data:
  # Base64 encoded values
  # DB_USER: appuser (encoded)
  DB_USER: YXBwdXNlcg==
  # DB_PASSWORD: apppassword (encoded)
  DB_PASSWORD: YXBwcGFzc3dvcmQ=