apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: javadb-app
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: java-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          value: "jdbc:mariadb://mariadb-service:3306/myapp"
        - name: DB_USERNAME
          value: "appuser"
        - name: DB_PASSWORD
          value: "apppassword"
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        dependsOn:
        - mariadb-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: javadb-app
spec:
  selector:
    app: java-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort